apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  api.json: |
    {
      "Widgetario__Theme": "dark",
      "ProductsAPI_URL": "http://products-api:80",
      "StockAPI_URL": "http://stock-api:8080"
    }
