apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: widgetario/frontend:latest   # Docker Hub image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort        # expose externally in kubeadm
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 80    # container port
      nodePort: 30080   # accessible on node at this port (30000-32767)
