apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: widgetario/products-api:21.03
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: products-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: example
---
apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  type: ClusterIP
  selector:
    app: products-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
