apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  ports:
  - port: 8081
    targetPort: 8080
    name: http
  selector:
    app: products-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
        component: api
        metrics: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: api
        image: widgetario/products-api:21.03
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_CONFIG_LOCATION
          value: /config/application.properties
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,prometheus,metrics,info"  # Enable all the needed endpoints
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: products-api-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: products-api-config
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://products-db-0.products-db:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password=postgres-password
    spring.jpa.hibernate.ddl-auto=update
    # Enable metrics and prometheus endpoints
    management.endpoints.web.exposure.include=health,prometheus,metrics,info
    management.endpoint.health.show-details=always
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true