apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        component: frontend
        metrics: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"  # Changed from 80 to 8080 - the metrics may be on a different port
    spec:
      containers:
      - name: web
        image: widgetario/web:21.03
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080  # Explicitly define metrics port if it exists
          name: metrics
        env:
        - name: WidgetarioTheme
          value: dark
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: MetricsEnabled
          value: "true"  # Explicitly enable metrics
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"

            cpu: "300m"
        volumeMounts:
        - name: config
          mountPath: /app/secrets
          readOnly: true
        - name: logs-volume
          mountPath: /logs
      # Add logging sidecar container to read logs
      - name: log-sidecar
        image: busybox:latest
        args: [/bin/sh, -c, 'tail -F /logs/app.log']
        volumeMounts:
        - name: logs-volume
          mountPath: /logs
      volumes:
      - name: config
        configMap:
          name: web-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  api.json: |
    {
      "ProductsApi": "http://products-api.default.svc.cluster.local:8081",
      "StockApi": "http://stock-api.default.svc.cluster.local:8082",
      "Metrics": {
        "Enabled": true,
        "Port": 8080
      }
    }
